### ISSUE TITLE
How can I update the database settings for a2billing-flask-api api?

### ISSUE THREAD

**Issue by rajeshbk042** [areski/a2billing-flask-api#4]
Hi,

I  have installed everything for [a2billing-flask-api](https://github.com/areski/a2billing-flask-api) except the database settings.

Currently, I am getting this error,  
`
peewee.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")`

Could you please suggests the file and its path to edit the database settings values?

**Comment by areski** [comment]
here https://github.com/areski/a2billing-flask-api/blob/master/a2billing_flask_api/config.py

**Comment by rajeshbk042** [comment]
Hi Areski Belaid,

Yes, its worked. Thank you very much

## 

_Thanks & Regards,_
_Rajesh_
